// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHntEVC2rSqp2TJU0FJxAM9nz8K4X18rU',
    appId: '1:419674672882:web:0185a9d15aedb512b88a6b',
    messagingSenderId: '419674672882',
    projectId: 'evntown-b5f0e',
    authDomain: 'evntown-b5f0e.firebaseapp.com',
    storageBucket: 'evntown-b5f0e.firebasestorage.app',
    measurementId: 'G-VP1WK8KEJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJje6to19sUT7M0WWbN1ql-jLnSgGjKtc',
    appId: '1:419674672882:android:8894cd209f14a3a6b88a6b',
    messagingSenderId: '419674672882',
    projectId: 'evntown-b5f0e',
    storageBucket: 'evntown-b5f0e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASy7RjuDsSKYMc8g49_i5mc0dA_1aeib4',
    appId: '1:419674672882:ios:ed1a0ebbd1b0abe5b88a6b',
    messagingSenderId: '419674672882',
    projectId: 'evntown-b5f0e',
    storageBucket: 'evntown-b5f0e.firebasestorage.app',
    iosBundleId: 'com.example.eventown',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASy7RjuDsSKYMc8g49_i5mc0dA_1aeib4',
    appId: '1:419674672882:ios:ed1a0ebbd1b0abe5b88a6b',
    messagingSenderId: '419674672882',
    projectId: 'evntown-b5f0e',
    storageBucket: 'evntown-b5f0e.firebasestorage.app',
    iosBundleId: 'com.example.eventown',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHntEVC2rSqp2TJU0FJxAM9nz8K4X18rU',
    appId: '1:419674672882:web:01dfdf95b660e094b88a6b',
    messagingSenderId: '419674672882',
    projectId: 'evntown-b5f0e',
    authDomain: 'evntown-b5f0e.firebaseapp.com',
    storageBucket: 'evntown-b5f0e.firebasestorage.app',
    measurementId: 'G-EMMMB4WJNP',
  );
}
